name: Dev CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10.10]

    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      SUPERUSER_PASSWORD: ${{ secrets.SUPERUSER_PASSWORD }}
      TESTUSER_PASSWORD: ${{ secrets.TESTUSER_PASSWORD }}
      ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
      DEBUG: ${{ secrets.DEBUG }}
      LANGUAGE_CODE: "en-us"
      TIME_ZONE: "UTC"
      USE_TZ: ${{ secrets.USE_TZ }}
      STATIC_URL: ${{ secrets.STATIC_URL }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.4.2
      - name: Install Dependencies
        run: |
          cd src
          poetry install
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Validate Code
        run: |
          cd src
          pytest